name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Run Maven tests
        run: mvn clean verify

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.zip
          unzip allure-2.18.1.zip
          sudo mv allure-2.18.1 /usr/local/bin/allure
          sudo ln -s /usr/local/bin/allure/allure /usr/local/bin/allure

      - name: Generate Allure HTML report
        run: allure generate target/allure-results --clean --output target/allure-report

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
